### PR TITLE
checking out Codecov uploader

### PR DESCRIPTION
**Pull request by stevepeak**

### CODE REVIEW

**Comment by Jericho** [comment]
`cat coverage.xml`
This command simply displays the content of the file (right?) and therefore isn't necessary (right?).

`curl https://codecov.io/bash > temp.sh`
This may or may not work depending on Windows being able to automatically locate 'curl.exe' on the local machine. In my case, curl.exe is present in the 'git For Windows' folder but Windows wasn't able to locate it. I didn't investigate to figure out why, but I'm guessing the location of 'git For Windows' is not in my PATH environment variable. 

As an alternative to curl, we should use the following PowerShell command: 
`(New-Object System.Net.WebClient).DownloadFile("https://codecov.io/bash", ".\CodecovUploader.sh")`

`bash temp.sh`
this can be replaced with ".\CodecovUploader.sh" (without quotes). Windows will automatically determine the appropriate interpreter for .sh files (which, in my case, is sh.exe bundled with git For Windows) instead of hardcoding "bash" which may or may not be automatically located by Windows.

_The uploader_
Now that you have removed the references to python, I can try to run the uploader. However, I'm getting the following error: 
image

Maybe it has to do with the fact that I am attempting to run the script interactively as opposed to running it by my CI (AppVeyor)? Maybe it's assuming a given environment variable should be present and I haven't provided it? Anyway, I'm continuing my research but let me know if you have ideas.

**Comment by stevepeak** [comment]
Thanks @Jericho for jumping in!
- The `cat coverage.xml` was just for debugging purposes.
- I was trying to debug the output on my own and tried `curl https://codecov.io/bash > temp.sh` but I would like to use `bash <(curl -s https://codecov.io/bash)` all the time

I'm curious what is causing that error. But [here is the line](https://github.com/codecov/codecov-bash/blob/abe23f698a16e9ff8fd321c294634e4651dd93e1/codecov#L330) that likely caused this. Perhaps you can suggest a fix. Otherwise we can skip the error that produces and continue the script

**Comment by stevepeak** [comment]
Here is a potential fix by skipping the error: https://github.com/codecov/codecov-bash/blob/wip/codecov#L330

You can try this uploader via `bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/wip/codecov)`

**Comment by Jericho** [comment]
I don't understand what this line of code is trying to do. 

Also, I figured out that your uploader allows to disable the "gcov" feature which avoids the problematic line of code:
`.\CodecovUploader.sh -t <my token> -X gcov`

**Comment by stevepeak** [comment]
The `gcov` is used for C and added to the uploader to simplify some customers setup.

I'm glad this is working now!

**Comment by Jericho** [comment]
I was able to upload my first code coverage file, however I get the following error when I look at the report on Codecov web site:
image

**Comment by stevepeak** [comment]
Inspecting/patching now. Thanks!

**Comment by stevepeak** [comment]
I fixed that issue. But the reports are not looking accurate, so I'm going to review the created XML and figure out whats going on. 

It is attempting to use our partial line coverage feature, but the data does not seem to line up over the lines. Making good progress though!

**Comment by stevepeak** [comment]
I'm having trouble understanding the coverage.xml output. I'm searching around for some answers but coming up blank.

**Pull request closed without merging**
